name: Laravel Lint And Test

on:
  pull_request:
    branches: ['*']

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.3'

      - uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Laravel Pint
        run: composer pint:check

      - name: Setup DB
        run: sudo systemctl start mysql.service && mysql --user=root --password=root -e "CREATE DATABASE laravel"

      - name: Run Tests
        env:
          DB_PASSWORD: root
        run: composer test
